LIST P=16F84

TRISA EQU 05H 	;DECLARACION DEL REGISTRO TRISA (CONFIGURACION DEL PUERTO A)
PA EQU 05H 		;DECLARACION DEL PUERTO A
STATUS EQU 03H 	;DECLARACION DEL REGSITRO STATUS
VAR EQU 10H 	;DECLARACION DEL REGISTRO VAR (UTILIZADO COMO CONTADOR)
PB EQU 06H
TRISB EQU 06H
NUMBER EQU 11H
TX EQU 12H
R11 EQU 13H
VAR2 EQU 14H
DATO EQU 15H

	ORG 0 ;VECTOR DE INTERRUPCION DEL RESET

	BSF STATUS,5
	MOVLW H'FF'
	MOVWF TRISB
	MOVLW H'0F'
	MOVWF TRISA
	BCF STATUS,5
	BSF PA,4

INICIO BTFSS PA,0 ;SE PRGUNTA SI ESTA PRESIONADA LA TECLA 1
	GOTO UNO ;SI ESTA PRESIONADA LA TECLA 1
	BTFSS PA,1 ;SE PRGUNTA SI ESTA PRESIONADA LA TECLA 2
	GOTO DOS ;SI ESTA PRESIONADA LA TECLA 1
	BTFSS PA,2 ;SE PRGUNTA SI ESTA PRESIONADA LA TECLA 3
	GOTO TRES ;SI ESTA PRESIONADA LA TECLA 1
	BTFSS PA,3 ;SE PRGUNTA SI ESTA PRESIONADA LA TECLA 4
	GOTO CUATRO ;SI ESTA PRESIONADA LA TECLA 1
	CLRF DATO ;SE BORRA LA VARIABLE DATO
	GOTO INICIO ;VAMOS EL INICIO YA QUE NO HAY TECLA PRESIONADA

UNO 	MOVLW '1' 	;SE LE ASIGNA A W EL VALOR EN CODIGO ASCII PARA EL NUMERO 1
	MOVWF NUMBER 	;SE GUARDA EN LA VARIABLE NUMBER
	CALL TRANS 	;SE LLAMA A LA RUTINA TRANS PARA ENVIAR EL DATO AL PC
	GOTO INICIO 	;VAMOS A INICIO

DOS 	MOVLW '2' 	;SE LE ASIGNA A W EL VALOR EN CODIGO ASCII PARA EL NUMERO 2
	MOVWF NUMBER 	;SE GUARDA EN LA VARIABLE NUMBER
	CALL TRANS 	;SE LLAMA A LA RUTINA TRANS PARA ENVIAR EL DATO AL PC
	GOTO INICIO 	;VAMOS A INICIO

TRES 	MOVLW '3' 	;SE LE ASIGNA A W EL VALOR EN CODIGO ASCII PARA EL NUMERO 3
	MOVWF NUMBER 	;SE GUARDA EN LA VARIABLE NUMBER
	CALL TRANS 		;SE LLAMA A LA RUTINA TRANS PARA ENVIAR EL DATO AL PC
	GOTO INICIO 	;VAMOS A INICIO

CUATRO 	MOVLW '4' 	;SE LE ASIGNA A W EL VALOR EN CODIGO ASCII PARA EL NUMERO 4
		MOVWF NUMBER 	;SE GUARDA EN LA VARIABLE NUMBER
		CALL TRANS 		;SE LLAMA A LA RUTINA TRANS PARA ENVIAR EL DATO AL PC
		GOTO INICIO 	;VAMOS A INICIO

TRANS 	SUBWF DATO,0 		;SE RESTA EL VALOR DE W CON DATO PARA VER SI ES EL MISMO
;TODAVIA
		BTFSC STATUS,2 			;SE CHEQUEA QUE LA BANDERA DE Z SE ACTIVARA
		RETLW 0 				;COMO SE ACTIVO ENTONCES ES QUE NO SE HA SOLTADO LA TECLA Y
;YA SE TRANSMITIO

	CLRWDT 		;BORRA EL WATHDOG
	MOVF NUMBER,0 	;SE MUEVE EL VALOR A TRANSMITIR A W
	MOVWF DATO 		;SE MUEVE EL VALOR A LA VARIABLE DATO
	MOVWF TX 		;MUEVE EL DATO A TRANSMITIR A LA VARIABLE TX
	MOVLW .8 		;MUEVE EL VALOR DE 8 A W
	MOVWF R11 		;MUEVE EL VALOR DE 8 AL REGISTRO R11
	BCF PA,4 		;PONE A 0 EL VALOR DE PA,1 (BIT DE INICIO)
	CALL DELAY1 	;LLAMA A LA RUTINA DE RETARDO
XNEXT BCF PA,4 	;PONE A 0 EL PUERTO PA,1
	BCF STATUS,0 	;PONE A CERO LA BANDERA DE ACARREO EN STATUS
	RRF TX,1 		;ROTA EL VALOR DEL TX UN PASO A LA DERECHA
	BTFSC STATUS,0 	;CHEQUEA EL VALOR DE ACARREO
	BSF PA,4 		;PONE EN 1 EL BIT PA,1
	CALL DELAY1 	;LLAMA A LA RUTINA DE RETARDO
	DECFSZ R11,1 	;DECREMENTA LA VARIABLE R11 Y CHEQUEA QUE NO DIO CERO
	GOTO XNEXT 		;LLAMA A LA ETIQUETA XNEXT PARA TRANSMITIR OTRO BIT
	BSF PA,4 		;PONE EN 1 PA,0
	CALL DELAY1 	;LLAMA A LA RUTINA DE DELAY1
	RETLW 0 		;TERMINA LA SUBRUTINA
DELAY1 MOVLW .166 ;CARGA EL NUMERO 166 EN W
	MOVWF VAR2 		;CARGA EL VALOR EN VAR2
REDO 	NOP
	NOP
	DECFSZ VAR2,1 	;DECREMENTA Y VERIFICA QUE NO SEA CERO
	GOTO REDO
	RETLW 0
	END